### ISSUE TITLE
Need account to access survey

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/Faith-Trends#5]
Cannot access survey without having an account with FaithTrends - I tried using the “shareable link” option to send out the survey through my own email. When I clicked on the link, it took me to the login page for FaithTrends. So the survey is not accessible without an account.

**Comment by bikash02** [comment]
If you want to answer or to get response for the particular survey you have to create an account with faith trends,Otherwise we won't track the result or survey answer.

It can be possible without having an account but at this point you have to create an account get access to the survey.Should I change the code.Waiting for your reply.So please tell me what to do. @debdiproy @camerontrimble @rikalively

**Comment by rikalively** [comment]
Okay, that makes sense. That would be up to Cameron. 

Thank you

**Comment by camerontrimble** [comment]
People should be able to complete the survey without registering as a user. They should have that option to register, however, because we want them to subscribe to the service and send out their own surveys. 

We should be able to track their responses in our system because they are associated with a survey. 

Study https://www.surveymonkey.com/r/VNJ5H6B as an example. I can take the survey without having to register as a user.

**Comment by bikash02** [comment]
Thank you !! We'll update you very soon.
